name: Build macOS DMG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-dmg:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        
    - name: Build macOS app bundle
      run: |
        python setup.py py2app
        
    - name: Create DMG
      run: |
        dmgbuild -s dmg_settings.py "PDF Preflight Tool" "PDF-Preflight-Tool.dmg"
        
    - name: Upload DMG artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF-Preflight-Tool-DMG
        path: PDF-Preflight-Tool.dmg
        
    - name: Create Release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: PDF-Preflight-Tool.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}